// Enumerations and flag definitions for creature columns.
//
// Values mirror the corresponding HavenCore enums; see the creature template
// document in the knowledge base for the columns each one applies to.

import { SelectOption, FlagOption } from './itemOptions';

export const CREATURE_RANK: SelectOption[] = [
  { value: 0, name: 'Normal (0)' },
  { value: 1, name: 'Elite (1)' },
  { value: 2, name: 'Rare Elite (2)' },
  { value: 3, name: 'World Boss (3)' },
  { value: 4, name: 'Rare (4)' },
  { value: 5, name: 'Unknown (5)' },
  { value: 6, name: 'Weak (6)' },
];

export const CREATURE_UNIT_CLASS: SelectOption[] = [
  { value: 1, name: 'Warrior (1)' },
  { value: 2, name: 'Paladin (2)' },
  { value: 4, name: 'Rogue (4)' },
  { value: 8, name: 'Mage (8)' },
];

export const CREATURE_TYPE: SelectOption[] = [
  { value: 0, name: 'None (0)' },
  { value: 1, name: 'Beast (1)' },
  { value: 2, name: 'Dragonkin (2)' },
  { value: 3, name: 'Demon (3)' },
  { value: 4, name: 'Elemental (4)' },
  { value: 5, name: 'Giant (5)' },
  { value: 6, name: 'Undead (6)' },
  { value: 7, name: 'Humanoid (7)' },
  { value: 8, name: 'Critter (8)' },
  { value: 9, name: 'Mechanical (9)' },
  { value: 10, name: 'Not specified (10)' },
  { value: 11, name: 'Totem (11)' },
  { value: 12, name: 'Non-combat Pet (12)' },
  { value: 13, name: 'Gas Cloud (13)' },
  { value: 14, name: 'Wild Pet (14)' },
  { value: 15, name: 'Aberration (15)' },
];

export const CREATURE_FAMILY: SelectOption[] = [
  { value: 0, name: 'None (0)' },
  { value: 1, name: 'Wolf (1)' },
  { value: 2, name: 'Cat (2)' },
  { value: 3, name: 'Spider (3)' },
  { value: 4, name: 'Bear (4)' },
  { value: 5, name: 'Boar (5)' },
  { value: 6, name: 'Crocolisk (6)' },
  { value: 7, name: 'Carrion Bird (7)' },
  { value: 8, name: 'Crab (8)' },
  { value: 9, name: 'Gorilla (9)' },
  { value: 11, name: 'Raptor (11)' },
  { value: 12, name: 'Tallstrider (12)' },
  { value: 15, name: 'Felhunter (15)' },
  { value: 16, name: 'Voidwalker (16)' },
  { value: 17, name: 'Succubus (17)' },
  { value: 19, name: 'Doomguard (19)' },
  { value: 20, name: 'Scorpid (20)' },
  { value: 21, name: 'Turtle (21)' },
  { value: 23, name: 'Imp (23)' },
  { value: 24, name: 'Bat (24)' },
  { value: 25, name: 'Hyena (25)' },
  { value: 26, name: 'Bird of Prey (26)' },
  { value: 27, name: 'Wind Serpent (27)' },
  { value: 28, name: 'Remote Control (28)' },
  { value: 29, name: 'Felguard (29)' },
  { value: 30, name: 'Dragonhawk (30)' },
  { value: 31, name: 'Ravager (31)' },
  { value: 32, name: 'Warp Stalker (32)' },
  { value: 33, name: 'Sporebat (33)' },
  { value: 34, name: 'Nether Ray (34)' },
  { value: 35, name: 'Serpent (35)' },
  { value: 37, name: 'Moth (37)' },
  { value: 38, name: 'Chimaera (38)' },
  { value: 39, name: 'Devilsaur (39)' },
  { value: 40, name: 'Ghoul (40)' },
  { value: 41, name: 'Silithid (41)' },
  { value: 42, name: 'Worm (42)' },
  { value: 43, name: 'Rhino (43)' },
  { value: 44, name: 'Wasp (44)' },
  { value: 45, name: 'Core Hound (45)' },
  { value: 46, name: 'Spirit Beast (46)' },
  { value: 49, name: 'Water Elemental (49)' },
  { value: 50, name: 'Fox (50)' },
  { value: 51, name: 'Monkey (51)' },
  { value: 52, name: 'Dog (52)' },
  { value: 53, name: 'Beetle (53)' },
  { value: 55, name: 'Shale Spider (55)' },
  { value: 56, name: 'Zombie (56)' },
  { value: 68, name: 'Hydra (68)' },
  { value: 125, name: 'Crane (125)' },
  { value: 126, name: 'Water Strider (126)' },
  { value: 128, name: 'Quilen (128)' },
  { value: 129, name: 'Goat (129)' },
  { value: 130, name: 'Basilisk (130)' },
  { value: 138, name: 'Direhorn (138)' },
  { value: 149, name: 'Rylak (149)' },
  { value: 150, name: 'Riverbeast (150)' },
  { value: 151, name: 'Stag (151)' },
];

export const CREATURE_MOVEMENT_TYPE: SelectOption[] = [
  { value: 0, name: 'Idle / Stationary (0)' },
  { value: 1, name: 'Random Movement (1)' },
  { value: 2, name: 'Waypoint Movement (2)' },
];

export const CREATURE_NPC_FLAGS: FlagOption[] = [
  { bit: 0, name: 'GOSSIP - Provides gossip interaction options' },
  { bit: 1, name: 'QUESTGIVER - Offers or completes quests' },
  { bit: 2, name: 'UNK1 - Internal unk flag 1' },
  { bit: 3, name: 'UNK2 - Internal unk flag 2' },
  { bit: 4, name: 'TRAINER - General trainer' },
  { bit: 5, name: 'TRAINER_CLASS - Class abilities trainer' },
  { bit: 6, name: 'TRAINER_PROFESSION - Profession trainer' },
  { bit: 7, name: 'VENDOR - General items vendor' },
  { bit: 8, name: 'VENDOR_AMMO - General goods / ammo vendor' },
  { bit: 9, name: 'VENDOR_FOOD - Food & beverage vendor' },
  { bit: 10, name: 'VENDOR_POISON - Poison vendor' },
  { bit: 11, name: 'VENDOR_REAGENT - Reagents vendor' },
  { bit: 12, name: 'REPAIR - Equipment repairs' },
  { bit: 13, name: 'FLIGHTMASTER - Flight path taxi node master' },
  { bit: 14, name: 'SPIRITHEALER - Spirit healer' },
  { bit: 15, name: 'SPIRITGUIDE - Battleground spirit guide' },
  { bit: 16, name: 'INNKEEPER - Innkeeper / sets hearthstone' },
  { bit: 17, name: 'BANKER - Access player bank' },
  { bit: 18, name: 'PETITIONER - Guild/Arena charter petition vendor' },
  { bit: 19, name: 'TABARDDESIGNER - Guild tabard designer' },
  { bit: 20, name: 'BATTLEMASTER - Battleground queue master' },
  { bit: 21, name: 'AUCTIONEER - Auction house access' },
  { bit: 22, name: 'STABLEMASTER - Hunter pet stable master' },
  { bit: 23, name: 'GUILD_BANKER - Guild bank vault access' },
  { bit: 24, name: 'SPELLCLICK - Spellclick interaction' },
  { bit: 25, name: 'PLAYER_VEHICLE - Passenger vehicle seat mount' },
  { bit: 26, name: 'MAILBOX - Mailbox interaction' },
  { bit: 27, name: 'ARTIFACT_POWER_RESPEC - Artifact powers respec' },
  { bit: 28, name: 'TRANSMOGRIFIER - Transmogrification vendor' },
  { bit: 29, name: 'VAULTKEEPER - Void storage vendor' },
  { bit: 30, name: 'WILD_BATTLE_PET - Wild pet battle challenge target' },
  { bit: 31, name: 'BLACK_MARKET - Black market auction house' },
  { bit: 33, name: 'GARRISON_ARCHITECT - Garrison architect table' },
  { bit: 34, name: 'STEERING - Vehicle steering master' },
  { bit: 35, name: 'SHIPYARD_MISSION_NPC - Shipyard mission table' },
  { bit: 36, name: 'SHIPMENT_CRAFTER - Work orders / shipment crafter' },
  { bit: 37, name: 'GARRISON_MISSION_NPC - Garrison mission table' },
  { bit: 38, name: 'TRADESKILL_NPC - Tradeskill trainer/crafter' },
  { bit: 39, name: 'BLACK_MARKET_VIEW - BMAH remote viewer' },
  { bit: 40, name: 'CLASS_HALLS_RECRUITMENT - Class order hall recruiter' },
  { bit: 41, name: 'CLASS_HALLS_TALENT - Order hall talent researcher' },
  { bit: 42, name: 'CONTRIBUTION_COLLECTOR - Warfront contribution collector' },
];

export const UNIT_FLAGS: FlagOption[] = [
  { bit: 0, name: 'SERVER_CONTROLLED - Movement controlled by server' },
  { bit: 1, name: 'NON_ATTACKABLE - Cannot be attacked' },
  { bit: 2, name: 'REMOVE_CLIENT_CONTROL - Disables client control' },
  { bit: 3, name: 'PVP_ATTACKABLE - PvP attackable rules apply' },
  { bit: 4, name: 'RENAME - Renameable pet' },
  { bit: 5, name: 'PREPARATION - Don\'t consume reagents' },
  { bit: 6, name: 'UNK_6 - Unk 6' },
  { bit: 7, name: 'NOT_ATTACKABLE_1 - Non-PvP attackable' },
  { bit: 8, name: 'IMMUNE_TO_PC - Immune to players' },
  { bit: 9, name: 'IMMUNE_TO_NPC - Immune to NPCs' },
  { bit: 10, name: 'LOOTING - Playing looting animation' },
  { bit: 11, name: 'PET_IN_COMBAT - Pet in combat' },
  { bit: 12, name: 'PVP - PvP enabled' },
  { bit: 13, name: 'SILENCED - Unit is silenced' },
  { bit: 14, name: 'CANNOT_SWIM - Unit cannot swim' },
  { bit: 15, name: 'ONLY_SWIM - Unit is water-bound / only swim' },
  { bit: 16, name: 'UNK_16 - Unk 16' },
  { bit: 17, name: 'PACIFIED - Unit is pacified' },
  { bit: 18, name: 'STUNNED - Unit is stunned' },
  { bit: 19, name: 'IN_COMBAT - Unit is in combat' },
  { bit: 20, name: 'TAXI_FLIGHT - Unit on taxi flight' },
  { bit: 21, name: 'DISARMED - Melee disarmed' },
  { bit: 22, name: 'CONFUSED - Unit is confused' },
  { bit: 23, name: 'FLEEING - Unit is fearing/fleeing' },
  { bit: 24, name: 'PLAYER_CONTROLLED - Controlled by player' },
  { bit: 25, name: 'NOT_SELECTABLE - Cannot be targeted or selected' },
  { bit: 26, name: 'SKINNABLE - Can be skinned after loot' },
  { bit: 27, name: 'MOUNT - Unit is mounted' },
  { bit: 28, name: 'UNK_28 - Unk 28' },
  { bit: 29, name: 'FEIGN_DEATH - Unit is feigning death' },
  { bit: 30, name: 'SHEATHE - Weapons are sheathed' },
  { bit: 31, name: 'UNK_31 - Unk 31' },
];

export const UNIT_FLAGS2: FlagOption[] = [
  { bit: 0, name: 'FEIGN_DEATH - Unit is feigning death' },
  { bit: 1, name: 'HIDE_MODEL - Model hidden (shows equipment only)' },
  { bit: 2, name: 'IGNORE_REPUTATION - Ignores reputation checks' },
  { bit: 3, name: 'COMPREHEND_LANG - Comprehends all languages' },
  { bit: 4, name: 'MIRROR_IMAGE - Unit is mirror image' },
  { bit: 5, name: 'INSTANTLY_APPEAR_MODEL - Summons appear without fade' },
  { bit: 6, name: 'FORCE_MOVEMENT - Force movement' },
  { bit: 7, name: 'DISARM_OFFHAND - Offhand weapon disarmed' },
  { bit: 8, name: 'DISABLE_PRED_STATS - Disabled predicted stats' },
  { bit: 9, name: 'ALLOW_CHANGING_TALENTS - Change talents anywhere' },
  { bit: 10, name: 'DISARM_RANGED - Ranged weapon disarmed' },
  { bit: 11, name: 'REGENERATE_POWER - Regenerates energy/power' },
  { bit: 12, name: 'RESTRICT_PARTY_INTERACTION - Party/raid interact only' },
  { bit: 13, name: 'PREVENT_SPELL_CLICK - Disables spellclick' },
  { bit: 14, name: 'ALLOW_ENEMY_INTERACT - Enemies can interact' },
  { bit: 15, name: 'DISABLE_TURN - Cannot rotate/turn' },
  { bit: 16, name: 'UNK2 - Unk 2' },
  { bit: 17, name: 'PLAY_DEATH_ANIM - Plays death animation' },
  { bit: 18, name: 'ALLOW_CHEAT_SPELLS - Allows cheat spell attributes' },
  { bit: 20, name: 'UNK4 - Unk 4' },
  { bit: 21, name: 'UNK5 - Unk 5' },
  { bit: 22, name: 'UNK6 - Unk 6' },
  { bit: 23, name: 'NO_ACTIONS - Disable all unit actions' },
  { bit: 24, name: 'UNK8 - Unk 8' },
  { bit: 25, name: 'UPDATE_REACTION - Update reactions' },
  { bit: 26, name: 'SELECTION_DISABLED - Selection disabled even for GM' },
  { bit: 27, name: 'UNK11 - Unk 11' },
  { bit: 28, name: 'HIDE_HIGHLIGHT_AND_NAME - Cannot target, hides name' },
  { bit: 29, name: 'UNK13 - Unk 13' },
  { bit: 30, name: 'UNK14 - Unk 14' },
  { bit: 31, name: 'UNK15 - Unk 15' },
];

export const UNIT_FLAGS3: FlagOption[] = [
  { bit: 0, name: 'UNK0 (1)' },
  { bit: 1, name: 'UNCONSCIOUS_ON_DEATH - Unconscious on Death (2)' },
  { bit: 2, name: 'ALLOW_MOUNTED_COMBAT - Allow mounted combat (4)' },
  { bit: 3, name: 'GARRISON_PET - Garrison pet (8)' },
  { bit: 4, name: 'UI_CAN_GET_POSITION - UI Can Get Position (16)' },
  { bit: 5, name: 'AI_OBSTACLE (32)' },
  { bit: 6, name: 'ALTERNATIVE_DEFAULT_LANGUAGE (64)' },
  { bit: 7, name: 'SUPPRESS_ALL_NPC_FEEDBACK - Suppress all NPC feedback (128)' },
  { bit: 8, name: 'IGNORE_COMBAT - Ignore Combat (256)' },
  { bit: 9, name: 'SUPPRESS_NPC_FEEDBACK - Suppress NPC feedback (512)' },
  { bit: 10, name: 'UNK10 (1024)' },
  { bit: 11, name: 'UNK11 (2048)' },
  { bit: 12, name: 'UNK12 (4096)' },
  { bit: 13, name: 'FAKE_DEAD - Show as dead (8192)' },
  { bit: 14, name: 'NO_FACING_ON_INTERACT_AND_FAST_FACING_CHASE (16384)' },
  { bit: 15, name: 'UNTARGETABLE_FROM_UI - Untargetable from UI (32768)' },
  { bit: 16, name: 'NO_FACING_ON_INTERACT_WHILE_FAKE_DEAD (65536)' },
  { bit: 17, name: 'ALREADY_SKINNED (131072)' },
  { bit: 18, name: 'SUPPRESS_ALL_NPC_SOUNDS - Suppress all NPC sounds (262144)' },
  { bit: 19, name: 'SUPPRESS_NPC_SOUNDS - Suppress NPC sounds (524288)' },
  { bit: 20, name: 'ALLOW_INTERACTION_WHILE_IN_COMBAT - Allow Interaction While in Combat (1048576)' },
  { bit: 21, name: 'UNK21 (2097152)' },
  { bit: 22, name: 'DONT_FADE_OUT (4194304)' },
  { bit: 23, name: 'UNK23 (8388608)' },
  { bit: 24, name: 'FORCE_HIDE_NAMEPLATE (16777216)' },
  { bit: 25, name: 'UNK25 (33554432)' },
  { bit: 26, name: 'UNK26 (67108864)' },
  { bit: 27, name: 'UNK27 (134217728)' },
  { bit: 28, name: 'UNK28 (268435456)' },
  { bit: 29, name: 'UNK29 (536870912)' },
  { bit: 30, name: 'UNK30 (1073741824)' },
  { bit: 31, name: 'UNK31 (2147483648)' },
];

export const UNIT_DYN_FLAGS: FlagOption[] = [
  { bit: 1, name: 'HIDE_MODEL - Object model not shown (2)' },
  { bit: 2, name: 'LOOTABLE - Unit has loot sparkle (4)' },
  { bit: 3, name: 'TRACK_UNIT - Unit is tracked on minimap (8)' },
  { bit: 4, name: 'TAPPED - Tapped by player/group (16)' },
  { bit: 5, name: 'SPECIALINFO - Special info display (32)' },
  { bit: 6, name: 'DEAD - Unit is dead (64)' },
  { bit: 7, name: 'REFER_A_FRIEND - Refer a friend target (128)' },
];

export const CREATURE_TYPE_FLAGS: FlagOption[] = [
  { bit: 0, name: 'TAMEABLE_PET - Hunter can tame this creature' },
  { bit: 1, name: 'GHOST_VISIBLE - Visible to ghost / dead players' },
  { bit: 2, name: 'BOSS_MOB - Shows ?? level portrait, immune knockback' },
  { bit: 3, name: 'DO_NOT_PLAY_WOUND_PARRY_ANIMATION' },
  { bit: 4, name: 'HIDE_FACTION_TOOLTIP - Hides faction in tooltip' },
  { bit: 5, name: 'UNK5 - Sound related' },
  { bit: 6, name: 'SPELL_ATTACKABLE - Can be hit by spells' },
  { bit: 7, name: 'CAN_INTERACT_WHILE_DEAD - Interactable when dead' },
  { bit: 8, name: 'HERB_SKINNING_SKILL - Can be gathered by Herbalist' },
  { bit: 9, name: 'MINING_SKINNING_SKILL - Can be mined by Miner' },
  { bit: 10, name: 'DO_NOT_LOG_DEATH - Death omitted from combat log' },
  { bit: 11, name: 'MOUNTED_COMBAT_ALLOWED - Remains mounted in combat' },
  { bit: 12, name: 'CAN_ASSIST - Assists nearby friendly units' },
  { bit: 13, name: 'IS_PET_BAR_USED' },
  { bit: 14, name: 'MASK_UID' },
  { bit: 15, name: 'ENGINEERING_SKINNING_SKILL - Engineer salvageable' },
  { bit: 16, name: 'EXOTIC_PET - Hunter exotic pet (Beast Mastery)' },
  { bit: 17, name: 'USE_DEFAULT_COLLISION_BOX' },
  { bit: 18, name: 'IS_SIEGE_WEAPON' },
  { bit: 19, name: 'CAN_COLLIDE_WITH_MISSILES - Intercepts projectiles' },
  { bit: 20, name: 'HIDE_NAME_PLATE - Hides nameplate over creature' },
  { bit: 21, name: 'DO_NOT_PLAY_MOUNTED_ANIMATIONS' },
  { bit: 22, name: 'IS_LINK_ALL - Links aggro with entire group' },
  { bit: 23, name: 'INTERACT_ONLY_WITH_CREATOR' },
  { bit: 24, name: 'DO_NOT_PLAY_UNIT_EVENT_SOUNDS' },
  { bit: 25, name: 'HAS_NO_SHADOW_BLOB - No shadow blob beneath' },
  { bit: 26, name: 'TREAT_AS_RAID_UNIT - Targetable by raid spells' },
  { bit: 27, name: 'FORCE_GOSSIP - Shows single gossip option' },
  { bit: 28, name: 'DO_NOT_SHEATHE' },
  { bit: 29, name: 'DO_NOT_TARGET_ON_INTERACTION' },
  { bit: 30, name: 'DO_NOT_RENDER_OBJECT_NAME' },
  { bit: 31, name: 'UNIT_IS_QUEST_BOSS - Quest boss marker' },
];

export const CREATURE_TYPE_FLAGS2: FlagOption[] = [
  { bit: 0, name: 'UNK1 (1)' },
  { bit: 1, name: 'UNK2 (2)' },
  { bit: 2, name: 'UNK3 (4)' },
  { bit: 3, name: 'UNK4 (8)' },
  { bit: 4, name: 'UNK5 (16)' },
  { bit: 5, name: 'UNK6 (32)' },
  { bit: 6, name: 'UNK7 (64)' },
  { bit: 7, name: 'UNK8 (128)' },
];

export const CREATURE_FLAGS_EXTRA: FlagOption[] = [
  { bit: 0, name: 'INSTANCE_BIND - Binds instance to killer on death' },
  { bit: 1, name: 'CIVILIAN - Non-aggressive civilian (honorless)' },
  { bit: 2, name: 'NO_PARRY - Creature cannot parry attacks' },
  { bit: 3, name: 'NO_PARRY_HASTEN - No parry haste counterattack' },
  { bit: 4, name: 'NO_BLOCK - Creature cannot block' },
  { bit: 5, name: 'NO_CRUSH - Creature cannot land crushing blows' },
  { bit: 6, name: 'NO_XP_AT_KILL - No experience awarded on kill' },
  { bit: 7, name: 'TRIGGER - Invisible trigger / dummy NPC' },
  { bit: 8, name: 'NO_TAUNT - Immune to taunt and fixate effects' },
  { bit: 9, name: 'NO_MOVE_FLAGS_UPDATE - Static movement flags' },
  { bit: 14, name: 'WORLDEVENT - World event creature' },
  { bit: 15, name: 'GUARD - Guard creature (attacks criminals/PvP)' },
  { bit: 17, name: 'NO_CRIT - Creature cannot critically strike' },
  { bit: 18, name: 'NO_SKILLGAIN - Won\'t increase weapon skills' },
  { bit: 19, name: 'TAUNT_DIMINISH - Subject to taunt diminishing' },
  { bit: 20, name: 'ALL_DIMINISH - Subject to all CC diminishing returns' },
  { bit: 21, name: 'NO_PLAYER_DAMAGE_REQ - Kill credit without player tap' },
  { bit: 28, name: 'DUNGEON_BOSS - Dungeon boss marker (runtime)' },
  { bit: 29, name: 'IGNORE_PATHFINDING - Ignores navmesh/pathfinding' },
  { bit: 30, name: 'IMMUNITY_KNOCKBACK - Immune to knockback effects' },
];

export const INHABIT_TYPE_FLAGS: FlagOption[] = [
  { bit: 0, name: 'Ground - Can walk / move on terrain (1)' },
  { bit: 1, name: 'Water - Can swim in water (2)' },
  { bit: 2, name: 'Flying - Can fly in air (4)' },
  { bit: 3, name: 'Rooted - Completely stationary (8)' },
];

export const MECHANIC_IMMUNE_MASK: FlagOption[] = [
  { bit: 0, name: 'Charm (1)' },
  { bit: 1, name: 'Disoriented (2)' },
  { bit: 2, name: 'Disarm (4)' },
  { bit: 3, name: 'Distract (8)' },
  { bit: 4, name: 'Fear (16)' },
  { bit: 5, name: 'Grip / Death Grip (32)' },
  { bit: 6, name: 'Root (64)' },
  { bit: 7, name: 'Slow Attack / Pacify (128)' },
  { bit: 8, name: 'Silence (256)' },
  { bit: 9, name: 'Sleep (512)' },
  { bit: 10, name: 'Snare / Movement Slow (1024)' },
  { bit: 11, name: 'Stun (2048)' },
  { bit: 12, name: 'Freeze (4096)' },
  { bit: 13, name: 'Knockout (8192)' },
  { bit: 14, name: 'Bleed (16384)' },
  { bit: 15, name: 'Bandage (32768)' },
  { bit: 16, name: 'Polymorph (65536)' },
  { bit: 17, name: 'Banish (131072)' },
  { bit: 18, name: 'Shield (262144)' },
  { bit: 19, name: 'Shackle (524288)' },
  { bit: 20, name: 'Mount (1048576)' },
  { bit: 21, name: 'Infected (2097152)' },
  { bit: 22, name: 'Turn Undead (4194304)' },
  { bit: 23, name: 'Horror (8388608)' },
  { bit: 24, name: 'Invulnerability (16777216)' },
  { bit: 25, name: 'Interrupt (33554432)' },
  { bit: 26, name: 'Daze (67108864)' },
  { bit: 27, name: 'Discovery (134217728)' },
  { bit: 28, name: 'Immune Shield (268435456)' },
  { bit: 29, name: 'Sapped (536870912)' },
  { bit: 30, name: 'Enraged (1073741824)' },
  { bit: 31, name: 'Wounded (2147483648)' },
];

export const SPELL_SCHOOL_IMMUNE_MASK: FlagOption[] = [
  { bit: 0, name: 'Normal / Physical (1)' },
  { bit: 1, name: 'Holy (2)' },
  { bit: 2, name: 'Fire (4)' },
  { bit: 3, name: 'Nature (8)' },
  { bit: 4, name: 'Frost (16)' },
  { bit: 5, name: 'Shadow (32)' },
  { bit: 6, name: 'Arcane (64)' },
];

/** Damage school dealt by melee attacks, from the core's `SpellSchools`. */
export const SPELL_SCHOOLS: SelectOption[] = [
  { value: 0, name: 'Normal / Physical (0)' },
  { value: 1, name: 'Holy (1)' },
  { value: 2, name: 'Fire (2)' },
  { value: 3, name: 'Nature (3)' },
  { value: 4, name: 'Frost (4)' },
  { value: 5, name: 'Shadow (5)' },
  { value: 6, name: 'Arcane (6)' },
];

/**
 * Expansion levels, from the core's `Expansions`.
 *
 * `-1` is the "current expansion" sentinel used by `HealthScalingExpansion`.
 * Values are rejected by the core above Battle for Azeroth.
 */
export const EXPANSIONS: SelectOption[] = [
  { value: -1, name: 'Current Expansion (-1)', comment: 'Scales with the live expansion' },
  { value: 0, name: 'Classic (0)' },
  { value: 1, name: 'The Burning Crusade (1)' },
  { value: 2, name: 'Wrath of the Lich King (2)' },
  { value: 3, name: 'Cataclysm (3)' },
  { value: 4, name: 'Mists of Pandaria (4)' },
  { value: 5, name: 'Warlords of Draenor (5)' },
  { value: 6, name: 'Legion (6)' },
  { value: 7, name: 'Battle for Azeroth (7)' },
];

/** Trainer kinds. The core defines only the class trainer. */
export const TRAINER_TYPE: SelectOption[] = [
  { value: 0, name: 'Class Trainer (0)' },
];

/** Player classes, used by `trainer_class`. */
export const PLAYER_CLASSES: SelectOption[] = [
  { value: 0, name: 'None (0)' },
  { value: 1, name: 'Warrior (1)' },
  { value: 2, name: 'Paladin (2)' },
  { value: 3, name: 'Hunter (3)' },
  { value: 4, name: 'Rogue (4)' },
  { value: 5, name: 'Priest (5)' },
  { value: 6, name: 'Death Knight (6)' },
  { value: 7, name: 'Shaman (7)' },
  { value: 8, name: 'Mage (8)' },
  { value: 9, name: 'Warlock (9)' },
  { value: 10, name: 'Monk (10)' },
  { value: 11, name: 'Druid (11)' },
  { value: 12, name: 'Demon Hunter (12)' },
];

/** Generic on/off options for the `tinyint` boolean columns. */
export const BOOLEAN_OPTIONS: SelectOption[] = [
  { value: 0, name: 'No (0)' },
  { value: 1, name: 'Yes (1)' },
];
