// Enumerations and flag definitions for gameobject columns, mirroring the
// corresponding HavenCore enums.

import { FlagOption, SelectOption } from './itemOptions';

// gameobject_template.type, from HavenCore's GameobjectTypes. The type selects
// what every Data0..Data33 column means; see gameObjectTypeData.ts.
export const GAMEOBJECT_TYPE_OPTIONS: SelectOption[] = [
  { value: 0, name: 'Door (0)' },
  { value: 1, name: 'Button (1)' },
  { value: 2, name: 'Quest Giver (2)' },
  { value: 3, name: 'Chest (3)' },
  { value: 4, name: 'Binder (4)' },
  { value: 5, name: 'Generic (5)' },
  { value: 6, name: 'Trap (6)' },
  { value: 7, name: 'Chair (7)' },
  { value: 8, name: 'Spell Focus (8)' },
  { value: 9, name: 'Text (9)' },
  { value: 10, name: 'Goober (10)' },
  { value: 11, name: 'Transport (11)' },
  { value: 12, name: 'Area Damage (12)' },
  { value: 13, name: 'Camera (13)' },
  { value: 14, name: 'Map Object (14)' },
  { value: 15, name: 'Map Object Transport (15)' },
  { value: 16, name: 'Duel Arbiter (16)' },
  { value: 17, name: 'Fishing Node (17)' },
  { value: 18, name: 'Ritual (18)' },
  { value: 19, name: 'Mailbox (19)' },
  { value: 20, name: 'Do Not Use (20)' },
  { value: 21, name: 'Guard Post (21)' },
  { value: 22, name: 'Spell Caster (22)' },
  { value: 23, name: 'Meeting Stone (23)' },
  { value: 24, name: 'Flag Stand (24)' },
  { value: 25, name: 'Fishing Hole (25)' },
  { value: 26, name: 'Flag Drop (26)' },
  { value: 27, name: 'Mini Game (27)' },
  { value: 28, name: 'Do Not Use 2 (28)' },
  { value: 29, name: 'Control Zone (29)' },
  { value: 30, name: 'Aura Generator (30)' },
  { value: 31, name: 'Dungeon Difficulty (31)' },
  { value: 32, name: 'Barber Chair (32)' },
  { value: 33, name: 'Destructible Building (33)' },
  { value: 34, name: 'Guild Bank (34)' },
  { value: 35, name: 'Trap Door (35)' },
  { value: 36, name: 'New Flag (36)' },
  { value: 37, name: 'New Flag Drop (37)' },
  { value: 38, name: 'Garrison Building (38)' },
  { value: 39, name: 'Garrison Plot (39)' },
  { value: 40, name: 'Client Creature (40)' },
  { value: 41, name: 'Client Item (41)' },
  { value: 42, name: 'Capture Point (42)' },
  { value: 43, name: 'Phaseable MO (43)' },
  { value: 44, name: 'Garrison Monument (44)' },
  { value: 45, name: 'Garrison Shipment (45)' },
  { value: 46, name: 'Garrison Monument Plaque (46)' },
  { value: 47, name: 'Item Forge (47)' },
  { value: 48, name: 'UI Link (48)' },
  { value: 49, name: 'Keystone Receptacle (49)' },
  { value: 50, name: 'Gathering Node (50)' },
  { value: 51, name: 'Challenge Mode Reward (51)' },
  { value: 52, name: 'Multi (52)' },
  { value: 53, name: 'Siegeable Multi (53)' },
  { value: 54, name: 'Siegeable MO (54)' },
  { value: 55, name: 'PvP Reward (55)' },
  { value: 56, name: 'Future Patch 1 (56)' },
  { value: 57, name: 'Future Patch 2 (57)' },
];

export const GAMEOBJECT_FLAGS: FlagOption[] = [
  { bit: 0, name: 'IN_USE - Disables interaction while animated' },
  { bit: 1, name: 'LOCKED - Requires key, spell or event to open' },
  { bit: 2, name: 'INTERACT_COND - Cannot interact without dynamic activation' },
  { bit: 3, name: 'TRANSPORT - Object can transport (elevator, boat)' },
  { bit: 4, name: 'NOT_SELECTABLE - Cannot be targeted or selected' },
  { bit: 5, name: 'NODESPAWN - Never despawns (e.g. doors)' },
  { bit: 6, name: 'AI_OBSTACLE - Registered in AI obstacle manager' },
  { bit: 7, name: 'FREEZE_ANIMATION - Keeps current animation frame' },
  { bit: 9, name: 'DAMAGED - Object is in damaged state' },
  { bit: 10, name: 'DESTROYED - Object is in destroyed state' },
  { bit: 19, name: 'INTERACT_DISTANCE_USES_TEMPLATE_MODEL' },
  { bit: 20, name: 'MAP_OBJECT - World map object model' },
];

export const GAMEOBJECT_DYNAMIC_FLAGS: FlagOption[] = [
  { bit: 0, name: 'LO_ACTIVATE - Activate object interaction' },
  { bit: 1, name: 'LO_ANIMATE - Animate object' },
  { bit: 2, name: 'NO_INTERACT - Disable player interaction' },
  { bit: 3, name: 'SPARKLE - Object sparkles (lootable / quest)' },
  { bit: 4, name: 'STOPPED - Object animation stopped' },
];

export const GAMEOBJECT_INVISIBILITY_TYPE: SelectOption[] = [
  { value: 0, name: 'None (0)' },
  { value: 1, name: 'General Invisibility (1)' },
  { value: 2, name: 'Stealth (2)' },
  { value: 3, name: 'Trap / Mine (3)' },
  { value: 4, name: 'Undead (4)' },
  { value: 5, name: 'Water (5)' },
  { value: 6, name: 'Drunk (6)' },
];
