// Enumerations and flag definitions for item columns, mirroring the
// corresponding HavenCore enums.

export interface SelectOption {
  value: number;
  name: string;
  comment?: string;
}

export interface FlagOption {
  bit: number;
  name: string;
  comment?: string;
}

export const ITEM_MATERIAL: SelectOption[] = [
  { value: -1, name: 'Consumables (Food, reagents, etc...)' },
  { value: 0, name: 'Not Defined' },
  { value: 1, name: 'Metal' },
  { value: 2, name: 'Wood' },
  { value: 3, name: 'Liquid' },
  { value: 4, name: 'Jewelry' },
  { value: 5, name: 'Chain' },
  { value: 6, name: 'Plate' },
  { value: 7, name: 'Cloth' },
  { value: 8, name: 'Leather' },
];

export const ITEM_CLASS: SelectOption[] = [
  { value: 0, name: 'Consumable' },
  { value: 1, name: 'Container' },
  { value: 2, name: 'Weapon' },
  { value: 3, name: 'Gem' },
  { value: 4, name: 'Armor' },
  { value: 5, name: 'Reagent' },
  { value: 6, name: 'Projectile' },
  { value: 7, name: 'Trade Goods' },
  { value: 8, name: 'Generic (OBSOLETE)' },
  { value: 9, name: 'Recipe' },
  { value: 10, name: 'Money (OBSOLETE)' },
  { value: 11, name: 'Quiver' },
  { value: 12, name: 'Quest' },
  { value: 13, name: 'Key' },
  { value: 14, name: 'Permanent' },
  { value: 15, name: 'Miscellaneous' },
  { value: 16, name: 'Glyph' },
  { value: 17, name: 'Battle Pet' },
  { value: 18, name: 'WoW Token' },
];

export const ITEM_SUBCLASS: Record<number, SelectOption[]> = {
  0: [
    { value: 0, name: 'Consumable' },
    { value: 1, name: 'Potion' },
    { value: 2, name: 'Elixir' },
    { value: 3, name: 'Flask' },
    { value: 4, name: 'Scroll' },
    { value: 5, name: 'Food & Drink' },
    { value: 6, name: 'Item Enhancement' },
    { value: 7, name: 'Bandage' },
    { value: 8, name: 'Other' },
  ],
  1: [
    { value: 0, name: 'Bag' },
    { value: 1, name: 'Soul Bag' },
    { value: 2, name: 'Herb Bag' },
    { value: 3, name: 'Enchanting Bag' },
    { value: 4, name: 'Engineering Bag' },
    { value: 5, name: 'Gem Bag' },
    { value: 6, name: 'Mining Bag' },
    { value: 7, name: 'Leatherworking Bag' },
    { value: 8, name: 'Inscription Bag' },
  ],
  2: [
    { value: 0, name: 'Axe (1H)' },
    { value: 1, name: 'Axe (2H)' },
    { value: 2, name: 'Bow' },
    { value: 3, name: 'Gun' },
    { value: 4, name: 'Mace (1H)' },
    { value: 5, name: 'Mace (2H)' },
    { value: 6, name: 'Polearm' },
    { value: 7, name: 'Sword (1H)' },
    { value: 8, name: 'Sword (2H)' },
    { value: 9, name: 'Warglaives' },
    { value: 10, name: 'Staff' },
    { value: 11, name: 'Bear Claws' },
    { value: 12, name: 'CatClaws' },
    { value: 13, name: 'Fist Weapon' },
    { value: 14, name: 'Miscellaneous Weapon' },
    { value: 15, name: 'Dagger' },
    { value: 16, name: 'Thrown' },
    { value: 17, name: 'Spear' },
    { value: 18, name: 'Crossbow' },
    { value: 19, name: 'Wand' },
    { value: 20, name: 'Fishing Pole' },
  ],
  3: [
    { value: 0, name: 'Red' },
    { value: 1, name: 'Blue' },
    { value: 2, name: 'Yellow' },
    { value: 3, name: 'Purple' },
    { value: 4, name: 'Green' },
    { value: 5, name: 'Orange' },
    { value: 6, name: 'Meta' },
    { value: 7, name: 'Simple' },
    { value: 8, name: 'Prismatic' },
  ],
  4: [
    { value: 0, name: 'Miscellaneous Armor' },
    { value: 1, name: 'Cloth' },
    { value: 2, name: 'Leather' },
    { value: 3, name: 'Mail' },
    { value: 4, name: 'Plate' },
    { value: 5, name: 'Buckler (OBSOLETE)' },
    { value: 6, name: 'Shield' },
    { value: 7, name: 'Libram' },
    { value: 8, name: 'Idol' },
    { value: 9, name: 'Totem' },
    { value: 10, name: 'Sigil' },
    { value: 11, name: 'Relic' },
  ],
  7: [
    { value: 0, name: 'Trade Goods' },
    { value: 1, name: 'Parts' },
    { value: 2, name: 'Explosives' },
    { value: 3, name: 'Devices' },
    { value: 4, name: 'Jewelcrafting' },
    { value: 5, name: 'Cloth' },
    { value: 6, name: 'Leather' },
    { value: 7, name: 'Metal & Stone' },
    { value: 8, name: 'Meat' },
    { value: 9, name: 'Herb' },
    { value: 10, name: 'Elemental' },
    { value: 11, name: 'Other' },
    { value: 12, name: 'Enchanting' },
    { value: 13, name: 'Materials' },
    { value: 14, name: 'Armor Enchantment' },
    { value: 15, name: 'Weapon Enchantment' },
  ],
  9: [
    { value: 0, name: 'Book' },
    { value: 1, name: 'Leatherworking' },
    { value: 2, name: 'Tailoring' },
    { value: 3, name: 'Engineering' },
    { value: 4, name: 'Blacksmithing' },
    { value: 5, name: 'Cooking' },
    { value: 6, name: 'Alchemy' },
    { value: 7, name: 'First Aid' },
    { value: 8, name: 'Enchanting' },
    { value: 9, name: 'Fishing' },
    { value: 10, name: 'Jewelcrafting' },
    { value: 11, name: 'Inscription' },
  ],
  12: [{ value: 0, name: 'Quest' }],
  13: [
    { value: 0, name: 'Key' },
    { value: 1, name: 'Lockpick' },
  ],
  15: [
    { value: 0, name: 'Junk' },
    { value: 1, name: 'Reagent' },
    { value: 2, name: 'Companion Pet' },
    { value: 3, name: 'Holiday' },
    { value: 4, name: 'Other' },
    { value: 5, name: 'Mount' },
  ],
  16: [
    { value: 1, name: 'Warrior' },
    { value: 2, name: 'Paladin' },
    { value: 3, name: 'Hunter' },
    { value: 4, name: 'Rogue' },
    { value: 5, name: 'Priest' },
    { value: 6, name: 'Death Knight' },
    { value: 7, name: 'Shaman' },
    { value: 8, name: 'Mage' },
    { value: 9, name: 'Warlock' },
    { value: 10, name: 'Monk' },
    { value: 11, name: 'Druid' },
    { value: 12, name: 'Demon Hunter' },
  ],
};

export const ITEM_QUALITY: SelectOption[] = [
  { value: 0, name: 'Grey (Poor)' },
  { value: 1, name: 'White (Common)' },
  { value: 2, name: 'Green (Uncommon)' },
  { value: 3, name: 'Blue (Rare)' },
  { value: 4, name: 'Purple (Epic)' },
  { value: 5, name: 'Orange (Legendary)' },
  { value: 6, name: 'Red / Gold (Artifact)' },
  { value: 7, name: 'Cyan (Heirloom / Bind to Account)' },
  { value: 8, name: 'Teal (WoW Token)' },
];

export const INVENTORY_TYPE: SelectOption[] = [
  { value: 0, name: 'Non-equippable' },
  { value: 1, name: 'Head' },
  { value: 2, name: 'Neck' },
  { value: 3, name: 'Shoulder' },
  { value: 4, name: 'Shirt' },
  { value: 5, name: 'Chest' },
  { value: 6, name: 'Waist' },
  { value: 7, name: 'Legs' },
  { value: 8, name: 'Feet' },
  { value: 9, name: 'Wrists' },
  { value: 10, name: 'Hands' },
  { value: 11, name: 'Finger' },
  { value: 12, name: 'Trinket' },
  { value: 13, name: 'One-Hand Weapon' },
  { value: 14, name: 'Shield' },
  { value: 15, name: 'Ranged (Bows/Guns)' },
  { value: 16, name: 'Cloak' },
  { value: 17, name: 'Two-Hand Weapon' },
  { value: 18, name: 'Bag' },
  { value: 19, name: 'Tabard' },
  { value: 20, name: 'Robe' },
  { value: 21, name: 'Main Hand Weapon' },
  { value: 22, name: 'Off Hand Weapon' },
  { value: 23, name: 'Held In Off-hand' },
  { value: 24, name: 'Ammo' },
  { value: 25, name: 'Thrown' },
  { value: 26, name: 'Ranged Right (Wands)' },
  { value: 27, name: 'Quiver' },
  { value: 28, name: 'Relic' },
];

export const ITEM_BONDING: SelectOption[] = [
  { value: 0, name: 'No Binding' },
  { value: 1, name: 'Binds on Pickup (BoP)' },
  { value: 2, name: 'Binds on Equip (BoE)' },
  { value: 3, name: 'Binds on Use (BoU)' },
  { value: 4, name: 'Quest Item' },
  { value: 5, name: 'Quest Item (No trade)' },
];

export const ITEM_SHEAT: SelectOption[] = [
  { value: 0, name: 'None' },
  { value: 1, name: 'Two Handed Weapon - Diagonally on Back' },
  { value: 2, name: 'Staff - Diagonally on Back (Upwards)' },
  { value: 3, name: 'One Handed - Hip (Left Side)' },
  { value: 4, name: 'Shield - Middle of Back' },
  { value: 5, name: 'Off Hand - Hip (Right Side)' },
  { value: 6, name: 'Bow / Gun - Back' },
];

export const TOTEM_CATEGORY: SelectOption[] = [
  { value: 0, name: 'None' },
  { value: 1, name: 'Skinning Knife (OLD)' },
  { value: 2, name: 'Earth Totem' },
  { value: 3, name: 'Air Totem' },
  { value: 4, name: 'Fire Totem' },
  { value: 5, name: 'Water Totem' },
  { value: 6, name: 'Runed Copper Rod' },
  { value: 7, name: 'Runed Silver Rod' },
  { value: 8, name: 'Runed Golden Rod' },
  { value: 9, name: 'Runed Truesilver Rod' },
  { value: 10, name: 'Runed Arcanite Rod' },
  { value: 11, name: 'Mining Pick (OLD)' },
  { value: 12, name: "Philosopher's Stone" },
  { value: 13, name: 'Blacksmith Hammer (OLD)' },
  { value: 14, name: 'Arclight Spanner' },
  { value: 15, name: 'Gyromatic Micro-Adjustor' },
  { value: 21, name: 'Master Totem' },
  { value: 41, name: 'Runed Fel Iron Rod' },
  { value: 62, name: 'Runed Adamantite Rod' },
  { value: 63, name: 'Runed Eternium Rod' },
  { value: 81, name: 'Hollow Quill' },
  { value: 101, name: 'Runed Azurite Rod' },
  { value: 121, name: 'Virtuoso Inking Set' },
  { value: 141, name: 'Drums' },
  { value: 161, name: 'Gnomish Army Knife' },
  { value: 162, name: 'Blacksmith Hammer' },
  { value: 165, name: 'Mining Pick' },
  { value: 166, name: 'Skinning Knife' },
  { value: 167, name: 'Hammer Pick' },
  { value: 168, name: 'Bladed Pickaxe' },
  { value: 169, name: 'Flint and Tinder' },
  { value: 189, name: 'Runed Cobalt Rod' },
  { value: 190, name: 'Runed Titanium Rod' },
];

export const STAT_TYPE: SelectOption[] = [
  { value: 0, name: 'None' },
  { value: 3, name: 'Agility' },
  { value: 4, name: 'Strength' },
  { value: 5, name: 'Intellect' },
  { value: 6, name: 'Spirit (Legacy)' },
  { value: 7, name: 'Stamina' },
  { value: 12, name: 'Defense Rating' },
  { value: 13, name: 'Dodge Rating' },
  { value: 14, name: 'Parry Rating' },
  { value: 15, name: 'Block Rating' },
  { value: 32, name: 'Critical Strike Rating' },
  { value: 36, name: 'Haste Rating' },
  { value: 40, name: 'Versatility Rating' },
  { value: 45, name: 'Spell Power' },
  { value: 49, name: 'Mastery Rating' },
  { value: 57, name: 'PvP Power' },
  { value: 58, name: 'Amplify' },
  { value: 59, name: 'Multistrike' },
  { value: 60, name: 'Readiness' },
  { value: 61, name: 'Speed (Tertiary)' },
  { value: 62, name: 'Leech (Tertiary)' },
  { value: 63, name: 'Avoidance (Tertiary)' },
  { value: 64, name: 'Indestructible (Tertiary)' },
];

export const SOCKET_COLOR_OPTIONS: SelectOption[] = [
  { value: 0, name: 'None' },
  { value: 1, name: 'Meta' },
  { value: 2, name: 'Red' },
  { value: 4, name: 'Yellow' },
  { value: 8, name: 'Blue' },
  { value: 14, name: 'Prismatic (Hydraulic/Cogwheel)' },
];

export const BAG_FAMILY: FlagOption[] = [
  { bit: 0, name: 'Arrows / Ammo' },
  { bit: 1, name: 'Bullets' },
  { bit: 2, name: 'Soul Shards' },
  { bit: 3, name: 'Leatherworking Supplies' },
  { bit: 4, name: 'Inscription Supplies' },
  { bit: 5, name: 'Herbs' },
  { bit: 6, name: 'Enchanting Supplies' },
  { bit: 7, name: 'Engineering Supplies' },
  { bit: 8, name: 'Keys' },
  { bit: 9, name: 'Gems' },
  { bit: 10, name: 'Mining Supplies' },
  { bit: 11, name: 'Soulbound Equipment' },
  { bit: 12, name: 'Vanity Pets' },
  { bit: 13, name: 'Currency Tokens' },
  { bit: 14, name: 'Quest Items' },
  { bit: 15, name: 'Fishing Supplies' },
  { bit: 16, name: 'Cooking Supplies' },
];

export const ITEM_FLAGS: FlagOption[] = [
  { bit: 0, name: 'NO_PICKUP' },
  { bit: 1, name: 'CONJURED - Disappears on logout' },
  { bit: 2, name: 'HAS_LOOT - Item can be right-clicked to open loot' },
  { bit: 3, name: 'HEROIC_TOOLTIP - Displays green Heroic text' },
  { bit: 4, name: 'DEPRECATED - Cannot equip or use' },
  { bit: 5, name: 'NO_USER_DESTROY - Cannot be deleted by player' },
  { bit: 6, name: "PLAYERCAST - Spells are castable by player" },
  { bit: 7, name: 'NO_EQUIP_COOLDOWN - No 30s equip cooldown' },
  { bit: 8, name: 'MULTI_LOOT_QUEST' },
  { bit: 9, name: 'IS_WRAPPER - Can wrap gifts' },
  { bit: 10, name: 'USES_RESOURCES' },
  { bit: 11, name: 'MULTI_DROP - Looting does not remove from available pool' },
  { bit: 12, name: 'ITEM_PURCHASE_RECORD - Refundable to vendor for full currency' },
  { bit: 13, name: 'PETITION - Guild or arena charter' },
  { bit: 14, name: 'HAS_TEXT - Readable item with pages' },
  { bit: 15, name: 'NO_DISENCHANT' },
  { bit: 16, name: 'REAL_DURATION' },
  { bit: 17, name: 'NO_CREATOR' },
  { bit: 18, name: 'IS_PROSPECTABLE' },
  { bit: 19, name: 'UNIQUE_EQUIPPABLE - Can only equip one copy' },
  { bit: 20, name: 'IGNORE_FOR_AURAS' },
  { bit: 21, name: 'IGNORE_DEFAULT_ARENA_RESTRICTIONS' },
  { bit: 22, name: 'NO_DURABILITY_LOSS' },
  { bit: 23, name: 'USE_WHEN_SHAPESHIFTED' },
  { bit: 24, name: 'HAS_QUEST_GLOW' },
  { bit: 25, name: 'HIDE_UNUSABLE_RECIPE' },
  { bit: 26, name: 'NOT_USEABLE_IN_ARENA' },
  { bit: 27, name: 'IS_BOUND_TO_ACCOUNT - Account-bound mail' },
  { bit: 28, name: 'NO_REAGENT_COST' },
  { bit: 29, name: 'IS_MILLABLE' },
  { bit: 30, name: 'REPORT_TO_GUILD_CHAT' },
  { bit: 31, name: 'NO_PROGRESSIVE_LOOT' },
];

export const ITEM_FLAGS_EXTRA: FlagOption[] = [
  { bit: 0, name: 'FACTION_HORDE - Horde only' },
  { bit: 1, name: 'FACTION_ALLIANCE - Alliance only' },
  { bit: 2, name: 'DONT_IGNORE_BUY_PRICE - Gold required with ExtendedCost' },
  { bit: 3, name: 'CLASSIFY_AS_CASTER' },
  { bit: 4, name: 'CLASSIFY_AS_PHYSICAL' },
  { bit: 5, name: 'EVERYONE_CAN_ROLL_NEED' },
  { bit: 6, name: 'NO_TRADE_BIND_ON_ACQUIRE' },
  { bit: 7, name: 'CAN_TRADE_BIND_ON_ACQUIRE' },
  { bit: 8, name: 'CAN_ONLY_ROLL_GREED' },
  { bit: 9, name: 'CASTER_WEAPON' },
  { bit: 10, name: 'DELETE_ON_LOGIN' },
  { bit: 11, name: 'INTERNAL_ITEM' },
  { bit: 12, name: 'NO_VENDOR_VALUE' },
  { bit: 13, name: 'SHOW_BEFORE_DISCOVERED' },
  { bit: 14, name: 'OVERRIDE_GOLD_COST' },
  { bit: 15, name: 'IGNORE_DEFAULT_RATED_BG_RESTRICTIONS' },
  { bit: 16, name: 'NOT_USABLE_IN_RATED_BG' },
  { bit: 17, name: 'BNET_ACCOUNT_TRADE_OK' },
  { bit: 18, name: 'CONFIRM_BEFORE_USE' },
  { bit: 19, name: 'REEVALUATE_BONDING_ON_TRANSFORM' },
  { bit: 20, name: 'NO_TRANSFORM_ON_CHARGE_DEPLETION' },
  { bit: 21, name: 'NO_ALTER_ITEM_VISUAL' },
  { bit: 22, name: 'NO_SOURCE_FOR_ITEM_VISUAL' },
  { bit: 23, name: 'IGNORE_QUALITY_FOR_ITEM_VISUAL_SOURCE' },
  { bit: 24, name: 'NO_DURABILITY' },
  { bit: 25, name: 'ROLE_TANK' },
  { bit: 26, name: 'ROLE_HEALER' },
  { bit: 27, name: 'ROLE_DAMAGE' },
  { bit: 28, name: 'CAN_DROP_IN_CHALLENGE_MODE' },
  { bit: 29, name: 'NEVER_STACK_IN_LOOT_UI' },
  { bit: 30, name: 'DISENCHANT_TO_LOOT_TABLE' },
  { bit: 31, name: 'USED_IN_A_TRADESKILL' },
];

export const ITEM_FLAGS_CUSTOM: FlagOption[] = [
  { bit: 0, name: 'CU_DURATION_REAL_TIME - Real-world seconds duration' },
  { bit: 1, name: 'CU_IGNORE_QUEST_STATUS' },
  { bit: 2, name: 'CU_FOLLOW_LOOT_RULES' },
];

export const ALLOWABLE_CLASSES: FlagOption[] = [
  { bit: 0, name: 'Warrior' },
  { bit: 1, name: 'Paladin' },
  { bit: 2, name: 'Hunter' },
  { bit: 3, name: 'Rogue' },
  { bit: 4, name: 'Priest' },
  { bit: 5, name: 'Death Knight' },
  { bit: 6, name: 'Shaman' },
  { bit: 7, name: 'Mage' },
  { bit: 8, name: 'Warlock' },
  { bit: 9, name: 'Monk' },
  { bit: 10, name: 'Druid' },
  { bit: 11, name: 'Demon Hunter' },
];

export const ALLOWABLE_RACES: FlagOption[] = [
  { bit: 0, name: 'Human' },
  { bit: 1, name: 'Orc' },
  { bit: 2, name: 'Dwarf' },
  { bit: 3, name: 'Night Elf' },
  { bit: 4, name: 'Undead' },
  { bit: 5, name: 'Tauren' },
  { bit: 6, name: 'Gnome' },
  { bit: 7, name: 'Troll' },
  { bit: 8, name: 'Goblin' },
  { bit: 9, name: 'Blood Elf' },
  { bit: 10, name: 'Draenei' },
  { bit: 21, name: 'Worgen' },
  { bit: 23, name: 'Pandaren (Neutral)' },
  { bit: 24, name: 'Pandaren (Alliance)' },
  { bit: 25, name: 'Pandaren (Horde)' },
  { bit: 26, name: 'Nightborne' },
  { bit: 27, name: 'Highmountain Tauren' },
  { bit: 28, name: 'Void Elf' },
  { bit: 29, name: 'Lightforged Draenei' },
  { bit: 30, name: 'Zandalari Troll' },
  { bit: 31, name: 'Kul Tiran' },
  { bit: 32, name: 'Dark Iron Dwarf' },
  { bit: 33, name: 'Vulpera' },
  { bit: 34, name: 'Mag\'har Orc' },
  { bit: 35, name: 'Mechagnome' },
];
