// SmartAI event, action and target definitions, mirroring the HavenCore enums.

export const SMART_SOURCE_TYPES: { [key: number]: string } = {
  0: 'CREATURE',
  1: 'GAMEOBJECT',
  2: 'AREATRIGGER',
  3: 'EVENT',
  4: 'GOSSIP',
  5: 'QUEST',
  6: 'SPELL',
  7: 'TRANSPORT',
  8: 'INSTANCE',
  9: 'TIMED_ACTIONLIST',
  10: 'TREASURE',
  11: 'DYNAMIC_OBJECT',
  12: 'SCENARIO',
};

export const SMART_EVENT_TYPES: { [key: number]: string } = {
  0: 'UPDATE_IC',
  1: 'UPDATE_OOC',
  2: 'HEALT_PCT',
  3: 'MANA_PCT',
  4: 'AGGRO',
  5: 'KILL',
  6: 'DEATH',
  7: 'EVADE',
  8: 'SPELLHIT',
  9: 'RANGE',
  10: 'OOC_LOS',
  11: 'RESPAWN',
  12: 'TARGET_HEALTH_PCT',
  13: 'VICTIM_CASTING',
  14: 'FRIENDLY_HEALTH',
  15: 'FRIENDLY_IS_CC',
  16: 'FRIENDLY_MISSING_BUFF',
  17: 'SUMMONED_UNIT',
  18: 'TARGET_MANA_PCT',
  19: 'ACCEPTED_QUEST',
  20: 'REWARD_QUEST',
  21: 'REACHED_HOME',
  22: 'RECEIVE_EMOTE',
  23: 'HAS_AURA',
  24: 'TARGET_BUFFED',
  25: 'RESET',
  26: 'IC_LOS',
  27: 'PASSENGER_BOARDED',
  28: 'PASSENGER_REMOVED',
  29: 'CHARMED',
  30: 'CHARMED_TARGET',
  31: 'SPELLHIT_TARGET',
  32: 'DAMAGED',
  33: 'DAMAGED_TARGET',
  34: 'MOVEMENTINFORM',
  35: 'SUMMON_DESPAWNED',
  36: 'CORPSE_REMOVED',
  37: 'AI_INIT',
  38: 'DATA_SET',
  39: 'WAYPOINT_START',
  40: 'WAYPOINT_REACHED',
  41: 'TRANSPORT_ADDPLAYER',
  42: 'TRANSPORT_ADDCREATURE',
  43: 'TRANSPORT_REMOVE_PLAYER',
  44: 'TRANSPORT_RELOCATE',
  45: 'INSTANCE_PLAYER_ENTER',
  46: 'AREATRIGGER_ONTRIGGER',
  47: 'QUEST_ACCEPTED',
  48: 'QUEST_OBJ_COPLETETION',
  49: 'QUEST_COMPLETION',
  50: 'QUEST_REWARDED',
  51: 'QUEST_FAIL',
  52: 'TEXT_OVER',
  53: 'RECEIVE_HEAL',
  54: 'JUST_SUMMONED',
  55: 'WAYPOINT_PAUSED',
  56: 'WAYPOINT_RESUMED',
  57: 'WAYPOINT_STOPPED',
  58: 'WAYPOINT_ENDED',
  59: 'TIMED_EVENT_TRIGGERED',
  60: 'UPDATE',
  61: 'LINK',
  62: 'GOSSIP_SELECT',
  63: 'JUST_CREATED',
  64: 'GOSSIP_HELLO',
  65: 'FOLLOW_COMPLETED',
  66: 'DUMMY_EFFECT',
  67: 'IS_BEHIND_TARGET',
  68: 'GAME_EVENT_START',
  69: 'GAME_EVENT_END',
  70: 'GO_STATE_CHANGED',
  71: 'GO_EVENT_INFORM',
  72: 'ACTION_DONE',
  73: 'ON_SPELLCLICK',
  74: 'FRIENDLY_HEALTH_PCT',
  75: 'DISTANCE_CREATURE',
  76: 'DISTANCE_GAMEOBJECT',
  77: 'COUNTER_SET',
  78: 'SCENE_START',
  79: 'SCENE_TRIGGER',
  80: 'SCENE_CANCEL',
  81: 'SCENE_COMPLETE',
};

export const SMART_ACTION_TYPES: { [key: number]: string } = {
  0: 'NONE',
  1: 'TALK',
  2: 'SET_FACTION',
  3: 'MORPH_TO_ENTRY_OR_MODEL',
  4: 'SOUND',
  5: 'PLAY_EMOTE',
  6: 'FAIL_QUEST',
  7: 'OFFER_QUEST',
  8: 'SET_REACT_STATE',
  9: 'ACTIVATE_GOBJECT',
  10: 'RANDOM_EMOTE',
  11: 'CAST',
  12: 'SUMMON_CREATURE',
  13: 'THREAT_SINGLE_PCT',
  14: 'THREAT_ALL_PCT',
  15: 'CALL_AREAEXPLOREDOREVENTHAPPENS',
  16: 'SET_INGAME_PHASE_GROUP',
  17: 'SET_EMOTE_STATE',
  18: 'SET_UNIT_FLAG',
  19: 'REMOVE_UNIT_FLAG',
  20: 'AUTO_ATTACK',
  21: 'ALLOW_COMBAT_MOVEMENT',
  22: 'SET_EVENT_PHASE',
  23: 'INC_EVENT_PHASE',
  24: 'EVADE',
  25: 'FLEE_FOR_ASSIST',
  26: 'CALL_GROUPEVENTHAPPENS',
  27: 'COMBAT_STOP',
  28: 'REMOVEAURASFROMSPELL',
  29: 'FOLLOW',
  30: 'RANDOM_PHASE',
  31: 'RANDOM_PHASE_RANGE',
  32: 'RESET_GOBJECT',
  33: 'CALL_KILLEDMONSTER',
  34: 'SET_INST_DATA',
  35: 'SET_INST_DATA64',
  36: 'UPDATE_TEMPLATE',
  37: 'DIE',
  38: 'SET_IN_COMBAT_WITH_ZONE',
  39: 'CALL_FOR_HELP',
  40: 'SET_SHEATH',
  41: 'FORCE_DESPAWN',
  42: 'SET_INVINCIBILITY_HP_LEVEL',
  43: 'MOUNT_TO_ENTRY_OR_MODEL',
  44: 'SET_INGAME_PHASE_ID',
  45: 'SET_DATA',
  47: 'SET_VISIBILITY',
  48: 'SET_ACTIVE',
  49: 'ATTACK_START',
  50: 'SUMMON_GO',
  51: 'KILL_UNIT',
  52: 'ACTIVATE_TAXI',
  53: 'WP_START',
  54: 'WP_PAUSE',
  55: 'WP_STOP',
  56: 'ADD_ITEM',
  57: 'REMOVE_ITEM',
  58: 'INSTALL_AI_TEMPLATE',
  59: 'SET_RUN',
  60: 'SET_DISABLE_GRAVITY',
  61: 'SET_SWIM',
  62: 'TELEPORT',
  63: 'SET_COUNTER',
  64: 'STORE_TARGET_LIST',
  65: 'WP_RESUME',
  66: 'SET_ORIENTATION',
  67: 'CREATE_TIMED_EVENT',
  68: 'PLAYMOVIE',
  69: 'MOVE_TO_POS',
  70: 'RESPAWN_TARGET',
  71: 'EQUIP',
  72: 'CLOSE_GOSSIP',
  73: 'TRIGGER_TIMED_EVENT',
  74: 'REMOVE_TIMED_EVENT',
  75: 'ADD_AURA',
  76: 'OVERRIDE_SCRIPT_BASE_OBJECT',
  77: 'RESET_SCRIPT_BASE_OBJECT',
  78: 'CALL_SCRIPT_RESET',
  79: 'SET_RANGED_MOVEMENT',
  80: 'CALL_TIMED_ACTIONLIST',
  81: 'SET_NPC_FLAG',
  82: 'ADD_NPC_FLAG',
  83: 'REMOVE_NPC_FLAG',
  84: 'SIMPLE_TALK',
  85: 'INVOKER_CAST',
  86: 'CROSS_CAST',
  87: 'CALL_RANDOM_TIMED_ACTIONLIST',
  88: 'CALL_RANDOM_RANGE_TIMED_ACTIONLIST',
  89: 'RANDOM_MOVE',
  90: 'SET_UNIT_FIELD_BYTES_1',
  91: 'REMOVE_UNIT_FIELD_BYTES_1',
  92: 'INTERRUPT_SPELL',
  93: 'SEND_GO_CUSTOM_ANIM',
  94: 'SET_DYNAMIC_FLAG',
  95: 'ADD_DYNAMIC_FLAG',
  96: 'REMOVE_DYNAMIC_FLAG',
  97: 'JUMP_TO_POS',
  98: 'SEND_GOSSIP_MENU',
  99: 'GO_SET_LOOT_STATE',
  100: 'SEND_TARGET_TO_TARGET',
  101: 'SET_HOME_POS',
  102: 'SET_HEALTH_REGEN',
  103: 'SET_ROOT',
  104: 'SET_GO_FLAG',
  105: 'ADD_GO_FLAG',
  106: 'REMOVE_GO_FLAG',
  107: 'SUMMON_CREATURE_GROUP',
  108: 'SET_POWER',
  109: 'ADD_POWER',
  110: 'REMOVE_POWER',
  111: 'GAME_EVENT_STOP',
  112: 'GAME_EVENT_START',
  113: 'START_CLOSEST_WAYPOINT',
  114: 'MOVE_OFFSET',
  115: 'RANDOM_SOUND',
  116: 'SET_CORPSE_DELAY',
  117: 'DISABLE_EVADE',
  118: 'GO_SET_GO_STATE',
  119: 'SET_CAN_FLY',
  120: 'REMOVE_AURAS_BY_TYPE',
  121: 'SET_SIGHT_DIST',
  122: 'FLEE',
  123: 'ADD_THREAT',
  124: 'LOAD_EQUIPMENT',
  125: 'TRIGGER_RANDOM_TIMED_EVENT',
  126: 'REMOVE_ALL_GAMEOBJECTS',
  127: 'STOP_MOTION',
  128: 'PLAY_ANIMKIT',
  129: 'SCENE_PLAY',
  130: 'SCENE_CANCEL',
  135: 'PLAY_CINEMATIC',
  136: 'SET_MOVEMENT_SPEED',
  137: 'PLAY_SPELL_VISUAL_KIT',
  138: 'FORCE_COMPLETE_QUEST',
  139: 'SAY',
  140: 'GET_SCENARIO',
  141: 'COMPLETE_SCENARIO_STEP',
  142: 'COMPLETE_SCENARIO',
  201: 'PLAY_SPELL_VISUAL',
  202: 'PLAY_ORPHAN_SPELL_VISUAL',
  203: 'CANCEL_VISUAL',
  204: 'CIRCLE_PATH',
  205: 'SET_OVERRIDE_ZONE_LIGHT',
  206: 'START_CONVERSATION',
  207: 'MODIFY_THREAT',
  208: 'SET_SPEED',
  209: 'IGNORE_PATHFINDING',
  210: 'SET_OVERRIDE_ZONE_MUSIC',
  211: 'SET_POWER_TYPE',
  212: 'SET_MAX_POWER',
  213: 'ADD_FLYING_MOVEMENT_FLAG',
  214: 'REMOVE_FLYING_MOVEMENT_FLAG',
  215: 'CAST_SPELL_OFFSET',
  1005: 'ENTER_LFG_QUEUE',
};

export const SMART_TARGET_TYPES: { [key: number]: string } = {
  0: 'NONE',
  1: 'SELF',
  2: 'VICTIM',
  3: 'HOSTILE_SECOND_AGGRO',
  4: 'HOSTILE_LAST_AGGRO',
  5: 'HOSTILE_RANDOM',
  6: 'HOSTILE_RANDOM_NOT_TOP',
  7: 'ACTION_INVOKER',
  8: 'POSITION',
  9: 'CREATURE_RANGE',
  10: 'CREATURE_GUID',
  11: 'CREATURE_DISTANCE',
  12: 'STORED',
  13: 'GAMEOBJECT_RANGE',
  14: 'GAMEOBJECT_GUID',
  15: 'GAMEOBJECT_DISTANCE',
  16: 'INVOKER_PARTY',
  17: 'PLAYER_RANGE',
  18: 'PLAYER_DISTANCE',
  19: 'CLOSEST_CREATURE',
  20: 'CLOSEST_GAMEOBJECT',
  21: 'CLOSEST_PLAYER',
  22: 'ACTION_INVOKER_VEHICLE',
  23: 'OWNER_OR_SUMMONER',
  24: 'THREAT_LIST',
  25: 'CLOSEST_ENEMY',
  26: 'CLOSEST_FRIENDLY',
  27: 'LOOT_RECIPIENTS',
  28: 'FARTHEST',
  29: 'VEHICLE_ACCESSORY',
  100: 'INVOKER_SUMMON',
};

export const SMART_EVENT_PARAM_NAMES: { [key: number]: string[] } = {
  0: ['InitialMin', 'InitialMax', 'RepeatMin', 'RepeatMax'],
  1: ['InitialMin', 'InitialMax', 'RepeatMin', 'RepeatMax'],
  2: ['HPMin%', 'HPMax%', 'RepeatMin', 'RepeatMax'],
  3: ['ManaMin%', 'ManaMax%', 'RepeatMin', 'RepeatMax'],
  4: ['NONE', '', '', ''],
  5: ['CooldownMin', 'CooldownMax', 'PlayerOnly', 'CreatureEntry'],
  6: ['NONE', '', '', ''],
  7: ['NONE', '', '', ''],
  8: ['SpellID', 'School', 'CooldownMin', 'CooldownMax'],
  9: ['MinDist', 'MaxDist', 'RepeatMin', 'RepeatMax'],
  10: ['NoHostile', 'MaxDist', 'CooldownMin', 'CooldownMax'],
  11: ['Type', 'MapID', 'AreaID', ''],
  12: ['HPMin%', 'HPMax%', 'RepeatMin', 'RepeatMax'],
  13: ['RepeatMin', 'RepeatMax', 'SpellID', ''],
  14: ['HPDeficit', 'Radius', 'RepeatMin', 'RepeatMax'],
  15: ['Radius', 'RepeatMin', 'RepeatMax', ''],
  16: ['SpellID', 'Radius', 'RepeatMin', 'RepeatMax'],
  17: ['CreatureID', 'CooldownMin', 'CooldownMax', ''],
  18: ['ManaMin%', 'ManaMax%', 'RepeatMin', 'RepeatMax'],
  19: ['QuestID', '', '', ''],
  20: ['QuestID', '', '', ''],
  21: ['NONE', '', '', ''],
  22: ['EmoteID', 'CooldownMin', 'CooldownMax', 'Condition'],
  23: ['SpellID', 'StackCount', 'RepeatMin', 'RepeatMax'],
  24: ['SpellID', 'StackCount', 'RepeatMin', 'RepeatMax'],
  25: ['NONE', '', '', ''],
  26: ['NoHostile', 'MaxDist', 'CooldownMin', 'CooldownMax'],
  27: ['CooldownMin', 'CooldownMax', '', ''],
  28: ['CooldownMin', 'CooldownMax', '', ''],
  29: ['OnRemove', '', '', ''],
  30: ['NONE', '', '', ''],
  31: ['SpellID', 'School', 'CooldownMin', 'CooldownMax'],
  32: ['MinDmg', 'MaxDmg', 'CooldownMin', 'CooldownMax'],
  33: ['MinDmg', 'MaxDmg', 'CooldownMin', 'CooldownMax'],
  34: ['MovementType', 'PointID', '', ''],
  35: ['Entry', 'CooldownMin', 'CooldownMax', ''],
  36: ['NONE', '', '', ''],
  37: ['NONE', '', '', ''],
  38: ['ID', 'Value', 'CooldownMin', 'CooldownMax'],
  39: ['PointID', 'PathID', '', ''],
  40: ['PointID', 'PathID', '', ''],
  41: ['NONE', '', '', ''],
  42: ['CreatureEntry', '', '', ''],
  43: ['NONE', '', '', ''],
  44: ['PointID', '', '', ''],
  45: ['Team', 'CooldownMin', 'CooldownMax', ''],
  46: ['TriggerID', '', '', ''],
  52: ['TextGroupID', 'CreatureEntry', '', ''],
  53: ['MinHeal', 'MaxHeal', 'CooldownMin', 'CooldownMax'],
  60: ['InitialMin', 'InitialMax', 'RepeatMin', 'RepeatMax'],
  62: ['MenuID', 'ActionID', '', ''],
  64: ['NoReportUse', '', '', ''],
  74: ['MinHpPct', 'MaxHpPct', 'RepeatMin', 'RepeatMax'],
  75: ['CreatureGUID', 'CreatureEntry', 'Distance', 'Repeat'],
  76: ['GoGUID', 'GoEntry', 'Distance', 'Repeat'],
  77: ['ID', 'Value', 'CooldownMin', 'CooldownMax'],
};

export const SMART_ACTION_PARAM_NAMES: { [key: number]: string[] } = {
  1: ['TextGroupID', 'Duration', 'UseTalkTarget', '', '', ''],
  2: ['FactionID', '', '', '', '', ''],
  3: ['CreatureEntry', 'ModelID', '', '', '', ''],
  4: ['SoundID', 'OnlySelf', '', '', '', ''],
  5: ['EmoteID', '', '', '', '', ''],
  6: ['QuestID', '', '', '', '', ''],
  7: ['QuestID', 'DirectAdd', '', '', '', ''],
  8: ['ReactState', '', '', '', '', ''],
  9: ['NONE', '', '', '', '', ''],
  10: ['Emote1', 'Emote2', 'Emote3', 'Emote4', 'Emote5', 'Emote6'],
  11: ['SpellID', 'CastFlags', 'TriggerFlags', 'TargetsLimit', '', ''],
  12: ['CreatureID', 'SummonType', 'DurationMS', 'AttackInvoker', 'IsPersonal', 'Data'],
  13: ['ThreatINC%', 'ThreatDEC%', '', '', '', ''],
  14: ['ThreatINC%', 'ThreatDEC%', '', '', '', ''],
  15: ['QuestID', '', '', '', '', ''],
  16: ['PhaseGroupID', 'Apply', '', '', '', ''],
  17: ['EmoteID', '', '', '', '', ''],
  18: ['UnitFlags', 'Target', '', '', '', ''],
  19: ['UnitFlags', 'Target', '', '', '', ''],
  20: ['AllowAttackState', '', '', '', '', ''],
  21: ['AllowCombatMovement', '', '', '', '', ''],
  22: ['EventPhase', '', '', '', '', ''],
  23: ['PhaseInc', 'PhaseDec', '', '', '', ''],
  28: ['SpellID', 'Charges', '', '', '', ''],
  29: ['Distance', 'Angle', 'EndCreatureEntry', 'Credit', 'CreditType', ''],
  30: ['Phase1', 'Phase2', 'Phase3', 'Phase4', 'Phase5', 'Phase6'],
  31: ['PhaseMin', 'PhaseMax', '', '', '', ''],
  33: ['CreatureID', '', '', '', '', ''],
  34: ['Field', 'Data', 'Type', '', '', ''],
  35: ['Field', '', '', '', '', ''],
  36: ['CreatureEntry', 'UpdateLevel', '', '', '', ''],
  39: ['Radius', 'WithEmote', '', '', '', ''],
  40: ['SheathState', '', '', '', '', ''],
  41: ['DelaySecs', 'Respawn', '', '', '', ''],
  42: ['MinHP', 'Percent', '', '', '', ''],
  43: ['CreatureEntry', 'ModelID', '', '', '', ''],
  44: ['PhaseID', 'Apply', '', '', '', ''],
  45: ['Field', 'Data', '', '', '', ''],
  47: ['VisibilityState', '', '', '', '', ''],
  48: ['ActiveState', '', '', '', '', ''],
  50: ['GameObjectID', 'DespawnSecs', '', '', '', ''],
  52: ['TaxiNodeID', '', '', '', '', ''],
  53: ['Run', 'PathID', 'Repeat', 'QuestID', 'DespawnTime', 'ReactState'],
  54: ['Delay', '', '', '', '', ''],
  55: ['DespawnTime', 'QuestID', 'Fail', '', '', ''],
  56: ['ItemID', 'Count', '', '', '', ''],
  57: ['ItemID', 'Count', '', '', '', ''],
  59: ['Run', 'Speed', 'SpeedDivider', '', '', ''],
  62: ['MapID', '', '', '', '', ''],
  63: ['CounterID', 'Value', 'Reset', '', '', ''],
  69: ['PointID', 'Transport', 'DisablePathfinding', 'ContactDist', '', ''],
  71: ['Entry', 'SlotMask', 'Slot1', 'Slot2', 'Slot3', ''],
  75: ['SpellID', '', '', '', '', ''],
  80: ['ActionListID', 'StopAfterCombat', 'TimerType', '', '', ''],
  81: ['NpcFlags', '', '', '', '', ''],
  82: ['NpcFlags', '', '', '', '', ''],
  83: ['NpcFlags', '', '', '', '', ''],
  84: ['TextGroupID', '', '', '', '', ''],
  85: ['SpellID', 'CastFlags', '', '', '', ''],
  86: ['SpellID', 'CastFlags', 'TargetType', 'TargetParam1', 'TargetParam2', 'TargetParam3'],
  87: ['ActionList1', 'ActionList2', 'ActionList3', 'ActionList4', 'ActionList5', 'ActionList6'],
  88: ['ActionListMin', 'ActionListMax', '', '', '', ''],
  89: ['MaxDist', '', '', '', '', ''],
  92: ['WithDelayed', 'SpellID', 'WithInstant', '', '', ''],
  97: ['SpeedXY', 'SpeedZ', '', '', '', ''],
  98: ['GossipMenuID', 'GossipNpcTextID', '', '', '', ''],
  101: ['NONE', '', '', '', '', ''],
  102: ['RegenHealth', '', '', '', '', ''],
  103: ['RootState', '', '', '', '', ''],
  104: ['GoFlags', '', '', '', '', ''],
  105: ['GoFlags', '', '', '', '', ''],
  106: ['GoFlags', '', '', '', '', ''],
  107: ['CreatureGroup', 'AttackInvoker', '', '', '', ''],
  108: ['PowerType', 'NewPower', '', '', '', ''],
  109: ['PowerType', 'NewPower', '', '', '', ''],
  110: ['PowerType', 'NewPower', '', '', '', ''],
  115: ['Sound1', 'Sound2', 'Sound3', 'Sound4', 'Sound5', 'OnlySelf'],
  118: ['GoState', '', '', '', '', ''],
  128: ['AnimKitID', 'Type', '', '', '', ''],
  138: ['QuestID', '', '', '', '', ''],
  139: ['ChatType', 'BroadcastTextID', 'Duration', 'UseSayTarget', '', ''],
  206: ['ConversationID', '', '', '', '', ''],
};

export const SMART_TARGET_PARAM_NAMES: { [key: number]: string[] } = {
  3: ['MaxDist', 'PlayerOnly', 'PowerType+1'],
  4: ['MaxDist', 'PlayerOnly', 'PowerType+1'],
  5: ['MaxDist', 'PlayerOnly', 'PowerType+1'],
  6: ['MaxDist', 'PlayerOnly', 'PowerType+1'],
  9: ['CreatureEntry', 'MinDist', 'MaxDist'],
  10: ['CreatureGUID', 'CreatureEntry', ''],
  11: ['CreatureEntry', 'MaxDist', ''],
  12: ['StoredID', '', ''],
  13: ['GoEntry', 'MinDist', 'MaxDist'],
  14: ['GoGUID', 'GoEntry', ''],
  15: ['GoEntry', 'MaxDist', ''],
  17: ['MinDist', 'MaxDist', ''],
  18: ['MaxDist', '', ''],
  19: ['CreatureEntry', 'MaxDist', 'Dead?'],
  20: ['GoEntry', 'MaxDist', ''],
  21: ['MaxDist', '', ''],
  24: ['MaxDist', '', ''],
  25: ['MaxDist', 'PlayerOnly', ''],
  26: ['MaxDist', 'PlayerOnly', ''],
  28: ['MaxDist', 'PlayerOnly', 'IsInLos'],
  29: ['SeatNumber', '', ''],
  100: ['SummonEntry', '', ''],
};
